apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefix-gateway
spec:
  stripPrefix:
    prefixes:
      - /api
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oathkeeper
spec:
  forwardAuth:
    address: http://oathkeeper.oosa-app.svc.cluster.local:8056/decisions
    authResponseHeaders:
      - Authorization
    authResponseHeadersRegex: ^X-User-
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: notify
spec:
  plugin:
    header2post:
      notifyurl: http://notifaction.oosa-app.svc.cluster.local:8080/notification
      forwardheaders: X-Forwarded-Host
      notifyheader: X-Notify
