---
kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
- name: merge api spec
  commands:
  - make merge-spec
- name: generate setting endpoint
  commands:
  - make gen-setting-json
- name: generate oath rules
  commands:
  - make gen-oath-rule
- name: build image
  commands:
  - docker build -t oosa-gw:dev .
- name: restart service
  commands:
  - docker-compose -f ./.docker/docker-test.yml down
  - docker-compose -f ./.docker/docker-test.yml up -d

trigger:
  branch:
  - test
...