---
kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
- name: merge api spec
  commands:
  - docker run -v $PWD:/workdir 94peter/openapi-cli:v1.5 /main ms -main /workdir/main_spec.yml -mergeDir /workdir/all_spec/ -output /workdir/doc/oosa.yml
- name: generate setting endpoint
  commands:
  - docker run -v $PWD:/workdir 94peter/openapi-cli:v1.5 /main togs -spec /workdir/doc/oosa.yml -output /workdir/settings/endpoint.json
- name: build image
  commands:
  - docker build --platform linux/amd64 -t oosa-gw:dev .
- name: restart service
  commands:
  - restart_arwoosa.sh

trigger:
  branch:
  - dev
...