---
kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
- name: merge api spec
  commands:
  - make merge-spec ENV=test
- name: generate setting endpoint
  commands:
  - make gen-setting-json ENV=test
- name: generate oath rules
  commands:
  - make gen-oath-rule ENV=test
- name: build image
  commands:
  - docker build -f ./.docker/Dockerfile -t oosa-gw:dev .
- name: restart service
  commands:
  - docker compose -f ./.docker-compose/docker-test.yml down
  - docker compose -f ./.docker-compose/docker-test.yml up -d

trigger:
  branch:
  - test
...