---
kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
- name: gen-all-config and restart service
  commands:
  - make gen-all ENV=test

- name: build gateway image
  commands:
  - docker build -f .docker/Dockerfile.gateway -t oosa-app-gw:test .

- name: build oathkeeper image
  commands:
  - docker build -f .docker/Dockerfile.oathkeeper -t oosa-app-gatewayoathkeeper:test .

- name: restart service
  commands:
  - docker compose -f ./.docker-compose/docker-test.yml down
  - docker compose -f ./.docker-compose/docker-test.yml up -d

- name: prune image
  commands:
  - docker image prune -f
  
trigger:
  branch:
  - main
  event:
  - push
...