networks:
  oosa-network:
    external: true
    driver: bridge
    name: oosa-network
    ipam:
      config:
        - subnet: 172.21.0.0/16

name: oosa
services:
  oosa_gateway:
    image: oosa-gw:dev
    container_name: oosa_gateway
    restart: always
    labels:
      - traefik.http.routers.gateway.entrypoints=web
      - traefik.http.routers.gateway.rule= (Host(`localhost`) || Host(`dev.oosa.life`)) && PathPrefix(`/api`)
      - traefik.http.routers.gateway.middlewares=api
    ports:
      - 6080:8000
    networks:
      - oosa-network
  oosa_gateway_auth:
    image: oosa-gw:dev
    container_name: oosa_gateway_auth
    restart: always
    labels:
      - traefik.http.routers.gateway-auth.entrypoints=web
      - traefik.http.routers.gateway-auth.rule= (Host(`auth-oosa.docker.localhost`) || Host(`dev-auth.oosa.life`)) && PathPrefix(`/api`)
      - traefik.http.routers.gateway-auth.middlewares=api-oathkeeper, api
    networks:
      - oosa-network
  api-oathkeeper:
    image: oryd/oathkeeper:v0.40.7-distroless
    depends_on:
    - oosa_gateway_auth
    labels:
    - traefik.http.middlewares.api-oathkeeper.forwardauth.address=http://api-oathkeeper:4456/decisions
    - traefik.http.middlewares.api-oathkeeper.forwardauth.authResponseHeaders=Authorization
    - traefik.http.middlewares.api-oathkeeper.forwardauth.authResponseHeadersRegex=^X-
    command: serve --config=/etc/config/oathkeeper/config.yaml
    volumes:
      - type: bind
        source: ./oathkeeper
        target: /etc/config/oathkeeper
    restart: on-failure
    networks:
      - oosa-network