networks:
  oosa-network:
    external: true
    driver: bridge
    name: oosa-network
    ipam:
      config:
        - subnet: 172.21.0.0/16

name: oosa
services:
  oosa_gateway:
    image: oosa-gw:dev
    container_name: oosa_gateway
    restart: always
    labels:
      - traefik.http.routers.gateway.entrypoints=web
      - traefik.http.routers.gateway.rule= (Host(`localhost`) || Host(`dev.oosa.life`)) && PathPrefix(`/api`)
      - traefik.http.routers.gateway.middlewares=api
    ports:
      - 6080:8080
    networks:
      - oosa-network