openapi: 3.0.3
info:
  title: OOSA API
  description: This is OOSA's API
  version: "1.0.0"
servers:
  - url: api.oosa.com 
    description: OOSA's API

components:
  securitySchemes:
    Bearer:
      type: apiKey
      in: header
      name: Bearer