openapi: 3.0.3
info:
  title: OOSA API
  description: This is OOSA's API
  version: "1.0.0"
servers:
  - url: oosa_user:6080
    description: OOSA_USER_SERVICE
  - url: oosa_rewild:6080
    description: OOSA_REWILD_SERVICE
  - url: dev-api.oosa.life 
    description: OOSA's Dev API

components:
  securitySchemes:
    Bearer:
      type: apiKey
      in: header
      name: Bearer