networks:
  oosa-network:
    external: true
    name: network.oosa

name: oosa-gateway
services:
  api-gateway:
    image: oosa-app-gw:test
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-gateway.entrypoints=web
      - traefik.http.routers.api-gateway.rule= Host(`dev.oosa.life`) && PathPrefix(`/api`)
      - traefik.http.services.api-gateway.loadbalancer.server.port=8080
      - traefik.http.middlewares.api.stripprefix.prefixes=/api
      - traefik.http.middlewares.corsheader.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE
      - traefik.http.middlewares.corsheader.headers.accesscontrolallowheaders=Cookie,Content-Type,Authorization
      - traefik.http.middlewares.corsheader.headers.accesscontrolalloworiginlist=https://dev.oosa.life,https://migema.oosa.life,https://frontend.oosa.life,http://localhost:3000,http://172.20.10.3:3000
      - traefik.http.middlewares.corsheader.headers.accesscontrolallowcredentials=true
      - traefik.http.middlewares.corsheader.headers.accesscontrolexposeheaders=Content-Length,Set-Cookie,Content-Type
      - traefik.http.middlewares.corsheader.headers.accesscontrolmaxage=3600
      - traefik.http.middlewares.corsheader.headers.addvaryheader=true
      - traefik.http.middlewares.app-header2post.plugin.header2post.notifyheader=X-Notify
      - traefik.http.middlewares.app-header2post.plugin.header2post.notifyurl=http://oosa_notify:9080/notification
      - traefik.http.middlewares.app-header2post.plugin.header2post.forwardheaders=X-Forwarded-Host
      - traefik.http.routers.api-gateway.middlewares=corsheader,app-header2post,api
    networks:
      - oosa-network
  api-gateway-auth:
    image: oosa-app-gw:test
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-gateway-auth.entrypoints=web
      - traefik.http.routers.api-gateway-auth.rule= (Host(`dev-auth.oosa.docker`) || Host(`dev-auth.oosa.life`)) && PathPrefix(`/api`)
      - traefik.http.services.api-gateway-auth.loadbalancer.server.port=8080
      - traefik.http.middlewares.app-auth-header2post.plugin.header2post.notifyheader=X-Notify
      - traefik.http.middlewares.app-auth-header2post.plugin.header2post.notifyurl=http://oosa_notify:9080/notification
      - traefik.http.middlewares.app-auth-header2post.plugin.header2post.forwardheaders=X-Forwarded-Host
      - traefik.http.routers.api-gateway-auth.middlewares=corsheader,app-auth-header2post,api,api-oathkeeper
    networks:
      - oosa-network
  api-oathkeeper:
    image: oosa-app-gatewayoathkeeper:test
    depends_on:
    - api-gateway-auth
    ports:
    - 4456:4456
    labels:
    - traefik.enable=true
    - traefik.http.middlewares.api-oathkeeper.forwardauth.address=http://api-oathkeeper:4456/decisions
    - traefik.http.middlewares.api-oathkeeper.forwardauth.authResponseHeaders=Authorization
    - traefik.http.middlewares.api-oathkeeper.forwardauth.authResponseHeadersRegex=^X-User-
    - traefik.http.routers.api-oathkeeper.entrypoints=web
    - traefik.http.routers.api-oathkeeper.rule= (Host(`dev-auth.oosa.docker`) || Host(`dev-auth.oosa.life`)) && PathPrefix(`/oathkeeper`)
    - traefik.http.services.api-oathkeeper.loadbalancer.server.port=4456
    - traefik.http.middlewares.api-oathkeeper-stripprefix.stripprefix.prefixes=/oathkeeper
    - traefik.http.routers.api-oathkeeper.middlewares=api-oathkeeper-stripprefix
    environment:
    - TRACING_PROVIDER=jaeger
    - TRACING_PROVIDERS_JAEGER_SAMPLING_SERVER_URL=http://jaeger:5778/sampling
    - TRACING_PROVIDERS_JAEGER_LOCAL_AGENT_ADDRESS=jaeger:6831
    command: serve --config=/etc/config/oathkeeper/config-test.yaml
    restart: always
    networks:
      - oosa-network
