openapi: 3.1.0
info:
  title: OOSA
  description: ''
  version: 1.0.0


servers:
- url: http://oosa_auth_test:6080
  description: OOSA_AUTH_TEST_SERVICE

paths:
  /test-auth:
    get:
      summary: Read Event Message Board
      deprecated: false
      description: Retrieve an event's message board
      operationId: getAuthHeader
      responses:
        '200':
          description: Array of EventMessageBoard Object
        '204':
          description: No event message board found
      security:
        - bearer: []
  /test-no-auth:
    get:
      summary: Read Event Message Board
      deprecated: false
      description: Retrieve an event's message board
      operationId: getNoAuthHeader
      responses:
        '200':
          description: Array of EventMessageBoard Object
        '204':
          description: No event message board found
      security: []
  /doc/{file}:
    get:
      summary: Read doc file
      deprecated: false
      description: Retrieve an event's message board
      operationId: getDoc
      parameters:
      - name: file
        in: path
        description: String ID of the event
        required: true
        example: ''
        schema:
          type: string
      responses:
        '200':
          description: Array of EventMessageBoard Object
        '204':
          description: No event message board found
      security: []